#!/bin/bash
SOFTPACK_ID=$1
DRIVERSPACK_ID=$2
INSTALL_LOCATION_ID=$3
SETTINGS_ID=$4
EFI_SYS_NAME=$5

XML_PARSER="get_data_from_components_xml.py"
SHARED_FUNCTIONS="shared_functions.sh"

#первым делом устанавливаем python3 в новую систему т.к. нужен для продолжения парсинга xml-файла
pacman -Syu python3 --noconfirm


source $SHARED_FUNCTIONS


DRIVERS_PACK="$(parse_xml driverspack get_pkgs_pacman)"
SOFT_PACK2="$(parse_xml softpack get_pkgs_pacman)"
USERNAME="$(parse_xml install_location get_username)"
MY_UID="$(parse_xml install_location get_useruid)"
HOSTNAME="$(parse_xml install_location get_hostname)"
MY_TIMEZONE="$(parse_xml settings get_timezone)"
MY_LOCALE="$(parse_xml settings get_default_locale)"
ALL_LOCALES="$(parse_xml settings get_locales)"

SOFTPACK_TWEAKS="$(parse_xml softpack get_softpack_tweaks)"

#проверяем, есть ли в настройках openbox
if [[ $SOFTPACK_TWEAKS == *"openbox"* ]]; then
    EXTRA_SETTINGS_4OPENBOX="true"
else
    EXTRA_SETTINGS_4OPENBOX="false"
fi


ADD_FILES_TO_HOME="true"
IS_CREATEROOT="false" #реализиуем чтение этих параметров из файла components.xml





# Установка часового пояса
ln -sf /usr/share/zoneinfo/$MY_TIMEZONE /etc/localtime
hwclock --systohc


# Установка языка и локали используя цикл и разделитель #
IFS='#' read -ra LOCALES <<< "$ALL_LOCALES"
for locale in "${LOCALES[@]}"; do
    echo "$locale" >> /etc/locale.gen
done
locale-gen
echo "LANG=$MY_LOCALE" >> /etc/locale.conf

VCONSOLE_STRINGS="$(parse_xml settings get_vconsole_strings)"
IFS='#' read -ra VCONSOLE_STRINGS_ARRAY <<< "$VCONSOLE_STRINGS"
for vconsole_string in "${VCONSOLE_STRINGS_ARRAY[@]}"; do
    echo "$vconsole_string" >> /etc/vconsole.conf
done


# Настройка hostname
echo $HOSTNAME > /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1 localhost" >> /etc/hosts
echo "127.0.1.1 $HOSTNAME.localdomain $HOSTNAME" >> /etc/hosts

# Установка пароля root
if [[ $IS_CREATEROOT = "true" ]]; then
    echo "Введите пароль для пользователя root:"
    passwd
fi


# Создание нового пользователя с UID и GID равными 1000 (или тем, что указано в начале файла)
groupadd -g $MY_UID $USERNAME
useradd -m -u $MY_UID -g $MY_UID -G users,wheel,storage,power -s /bin/bash $USERNAME


# Установка пароля для нового пользователя
echo "Введите пароль для пользователя $USERNAME:"
passwd $USERNAME

# устанавливаем sudo
# такие пакеты как coreutils и sed уже входят в состав base поэтому их установка избыточна
pacman -S sudo --noconfirm


# Установка всего дополнительного софта через pacman (кроме драйверов)
for package in $SOFT_PACK2; do
    echo "Установка пакета: $package и его зависимостей"
    pacman -S $package --noconfirm
done
# Установка драйверов
for package in $DRIVERS_PACK; do
    echo "Установка пакета: $package и его зависимостей"
    pacman -S $package --noconfirm
done


# Разрешение sudo для пользователя
#sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers


# Добавление пользователя в файл sudoers

mkdir -p /etc/sudoers.d
echo '#you can add rules here' > /etc/sudoers.d/rules-autogenerated
chmod 440 /etc/sudoers.d/rules-autogenerated
echo "#$USERNAME ALL=(ALL) ALL" | EDITOR='tee -a' visudo -f /etc/sudoers.d/rules-autogenerated
echo "#$USERNAME ALL=(ALL) NOPASSWD: ALL" | EDITOR='tee -a' visudo -f /etc/sudoers.d/rules-autogenerated
echo '#%wheel ALL=(ALL:ALL) ALL' | EDITOR='tee -a' visudo -f /etc/sudoers.d/rules-autogenerated
echo '#%wheel ALL=(ALL:ALL) NOPASSWD: ALL' | EDITOR='tee -a' visudo -f /etc/sudoers.d/rules-autogenerated
echo '#%sudo ALL=(ALL:ALL) ALL' | EDITOR='tee -a' visudo -f /etc/sudoers.d/rules-autogenerated
echo '%wheel ALL=(ALL:ALL) ALL' | EDITOR='tee -a' visudo -f /etc/sudoers.d/rules-autogenerated

#EDITOR="sed -i 's/^#[[:space:]]*%wheel[[:space:]]*ALL=(ALL:ALL)[[:space:]]*ALL/%wheel ALL=(ALL:ALL) ALL/'" visudo -f /etc/sudoers.d/rules-autogenerated



# Настройка хуков для mkinitcpio
sed -i "s/^HOOKS=(.*)/HOOKS=($(parse_xml install_location get_hooks))/" /etc/mkinitcpio.conf
mkinitcpio -P



# Установка загрузчика
pacman -S grub efibootmgr  --noconfirm
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=$EFI_SYS_NAME
grub-mkconfig -o /boot/grub/grub.cfg

# Делаем новую запись EFI загрузчиком по умолчанию
#BOOT_NUM=$(efibootmgr | grep $EFI_SYS_NAME | sed 's/Boot\([0-9a-fA-F]*\).*/\1/')
#efibootmgr -o $BOOT_NUM

#don't forget about update-grub ( grub-mkonfig -o /boot/grub/grub.cfg ) in the main linux system 
if [[ $EXTRA_SETTINGS_4OPENBOX = "true" ]]; then
    #добавление юзера в группы для работы звука
    #usermod -a -G audio,pulse-access $USERNAME
    usermod -a -G audio $USERNAME
    #также надо добавить в группу realtime, если установлен пакет realtime-privileges
    #добавление в группу video
    usermod -a -G video $USERNAME
    
    
    #настройка возможности монитирования дисков для группы storage без прав рута
    echo 'KERNEL=="sd[a-z][0-9]", GROUP="storage", MODE="0660"' > /etc/udev/rules.d/99-storage.rules
    echo 'KERNEL=="nvme0n[0-9]p[0-9]", GROUP="storage", MODE="0660"' >> /etc/udev/rules.d/99-storage.rules
    echo 'KERNEL=="sr0", GROUP="storage", MODE="0660"' > /etc/udev/rules.d/99-cdrom.rules
    
    # Настройка автозапуска PipeWire
    mkdir -p /home/$USERNAME/.config/systemd/user/default.target.wants/

    ln -sf /usr/lib/systemd/user/pipewire.service /home/$USERNAME/.config/systemd/user/default.target.wants/
    ln -sf /usr/lib/systemd/user/pipewire-pulse.service /home/$USERNAME/.config/systemd/user/default.target.wants/
    ln -sf /usr/lib/systemd/user/wireplumber.service /home/$USERNAME/.config/systemd/user/default.target.wants/
    
    # Установка правильных прав доступа
    chown -R $USERNAME:$USERNAME /home/$USERNAME/.config
    
    
    #su $USERNAME -c "systemctl --user enable pulseaudio.socket"
    #Or add it to your ~/.xinitrc, if you use it:
    
    # ~/.xinitrc
    # ...
    # /usr/bin/pipewire &
    # /usr/bin/pipewire-pulse &
    # /usr/bin/wireplumber &
    # exec openbox-session
    #------------------------------------------------------------------------------------
    
fi


#---------------------------------------------------------------

echo "настройка автозапуска NetworkManager для работы интернета"
ln -s /usr/lib/systemd/system/NetworkManager.service /etc/systemd/system/multi-user.target.wants/NetworkManager.service

#------------------------------------------------------------------------------------
#получаем список архивов для распаковки в домашнюю папку пользователя
ARCHIVES_4HOME="$(parse_xml softpack get_archs4home)"

if [[ $ADD_FILES_TO_HOME = "true" ]]; then
    #распаковка tar-архива в домашнюю папку пользователя
    #испльзуем цикл для распаковки всех архивов
    for archive in $ARCHIVES_4HOME; do
        tar --numeric-owner -xvf "/$archive" -C /home/$USERNAME
        chown -R $MY_UID:$MY_UID /home/$USERNAME/
        rm "/$archive"
    done
fi

# Выход из chroot
exit




